server:
  port: 8101
  address: localhost
spring:
  application:
    name: magnet-lucia
  data:
    mongodb:
      database: lucia
      host: localhost
      port: 27017
      repositories:
        enabled: true
eureka:
  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 10
    leaseExpirationDurationInSeconds: 20
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka
management:
  security:
    enabled: false

